<a href="https://colab.research.google.com/github/DiegoVianaR/analise-missoes-lunares/blob/Diego/Teste_Lunar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# importar dados missoes lunares
!git clone https://github.com/ChiaviniK/analise-missoes-lunares.git

fatal: destination path 'analise-missoes-lunares' already exists and is not an empty directory.

In [12]:
import pandas as pd
df_lua = pd.read_csv("/content/analise-missoes-lunares/Moonlanding.csv")
display(df_lua)

,Mission,Spacecraft,Launch Date,Carrier Rocket,Operator,Mission Type,Outcome,Additional Information
0,Pioneer 0 (Able I),Pioneer 0,17-Aug-58,Thor DM-18 Able I,United States USAF,Orbiter,Launch failure,First attempted launch beyond Earth orbit; fai...
1,Luna E-1 No.1,Luna E-1 No.1,23-Sep-58,Luna,Soviet Union OKB-1,Impactor,Launch failure,Failed to orbit; rocket disintegrated due to e...
2,Pioneer 1 (Able II),Pioneer 1,11-Oct-58,Thor DM-18 Able I,United States NASA,Orbiter,Launch failure,Failed to orbit; premature second-stage cutoff...
3,Luna E-1 No.2,Luna E-1 No.2,11-Oct-58,Luna,Soviet Union OKB-1,Impactor,Launch failure,Failed to orbit; carrier rocket exploded due t...
4,Pioneer 2 (Able III),Pioneer 2,08-Nov-58,Thor DM-18 Able I,United States NASA,Orbiter,Launch failure,Failed to orbit; premature second-stage cutoff...
...,...,...,...,...,...,...,...,...
161,Peregrine Mission One,Peregrine,08-Jan-24,Vulcan Centaur VC2,Astrobotic Technology,Lander,Spacecraft failure,Part of CLPS. Peregrine lander's reaction thru...
162,Peregrine Mission One,Colmena ? 5,08-Jan-24,Vulcan Centaur VC2,UNAM,Rovers,Precluded,Part of CLPS. Peregrine lander's reaction thru...
163,Peregrine Mission One,Iris,08-Jan-24,Vulcan Centaur VC2,CMU,Rover,Precluded,Part of CLPS. Peregrine lander's reaction thru...
164,IM-1,Nova-C Odysseus,14-Feb-24,Falcon 9 B5,Intuitive Machines,Lander,Operational,First Nova-C mission. Payloads successfully de...
165,IM-1,EagleCam,14-Feb-24,Falcon 9 B5,ERAU,Deployable camera (semi hard lander),Awaiting Deployment,First Nova-C mission. Payloads successfully de...

In [11]:
# Média de foguete utilizados
frequencia = df_lua["Carrier Rocket"].value_counts()

display(frequencia)

Carrier Rocket
Proton-K/D                  24
Molniya-M                   12
SLS Block 1                 11
Saturn V                    10
Luna                         9
Atlas LV-3 Agena-B           6
Atlas SLV-3 Agena-D          5
Molniya-L                    5
Long March 3C                4
Atlas LV-3C Centaur-D        4
Falcon 9 Block 5             4
Long March 3B                4
Long March 5                 4
Thor DM-18 Able I            3
  H-IIA                      3
Vulcan Centaur VC2           3
H-IIA 2022                   3
Atlas-D Able                 3
Atlas SLV-3C Centaur-D       3
Molniya                      3
Long March 4C                3
Juno II                      2
Delta E1                     2
Falcon 9                     2
Delta II 7925                2
PSLV-XL C11                  2
Atlas V 401                  2
Falcon 9 B5                  2
Delta 1913                   1
N1                           1
Delta II 7925-10             1
Delta II 6925                1
Mu-4S-II                     1
Mu-3S-II                     1
Delta 2914                   1
Atlas SLV-3D Centaur-D1A     1
Athena II                    1
Titan II (23)G Star-37FM     1
Delta II 7921H               1
Delta II 7920H               1
Long March 3A                1
M-V                          1
Delta II 7425-10             1
Ariane 5G                    1
Delta II 7925-10L            1
Delta II 7925-11L            1
Proton-K/DM3                 1
LVM3 M1                      1
Minotaur V                   1
Falcon 9 Full Thrust         1
Electron                     1
Ariane 5 ECA                 1
LVM3 M4                      1
Soyuz-2.1b/Fregat            1
Name: count, dtype: int64

In [13]:
# Média de foguetes utilizados
frequencia = (
    df_lua["Carrier Rocket"]
    .value_counts()
    .reset_index()
)

frequencia.columns = ["Modelo do Foguete", "Quantidade de Utilizações"]

display(frequencia)

           Modelo do Foguete  Quantidade de Utilizações
0                 Proton-K/D                         24
1                  Molniya-M                         12
2                SLS Block 1                         11
3                   Saturn V                         10
4                       Luna                          9
5         Atlas LV-3 Agena-B                          6
6        Atlas SLV-3 Agena-D                          5
7                  Molniya-L                          5
8              Long March 3C                          4
9      Atlas LV-3C Centaur-D                          4
10          Falcon 9 Block 5                          4
11             Long March 3B                          4
12              Long March 5                          4
13         Thor DM-18 Able I                          3
14                     H-IIA                          3
15        Vulcan Centaur VC2                          3
16                H-IIA 2022                          3
17              Atlas-D Able                          3
18    Atlas SLV-3C Centaur-D                          3
19                   Molniya                          3
20             Long March 4C                          3
21                   Juno II                          2
22                  Delta E1                          2
23                  Falcon 9                          2
24             Delta II 7925                          2
25               PSLV-XL C11                          2
26               Atlas V 401                          2
27               Falcon 9 B5                          2
28                Delta 1913                          1
29                        N1                          1
30          Delta II 7925-10                          1
31             Delta II 6925                          1
32                  Mu-4S-II                          1
33                  Mu-3S-II                          1
34                Delta 2914                          1
35  Atlas SLV-3D Centaur-D1A                          1
36                 Athena II                          1
37  Titan II (23)G Star-37FM                          1
38            Delta II 7921H                          1
39            Delta II 7920H                          1
40             Long March 3A                          1
41                       M-V                          1
42          Delta II 7425-10                          1
43                 Ariane 5G                          1
44         Delta II 7925-10L                          1
45         Delta II 7925-11L                          1
46              Proton-K/DM3                          1
47                   LVM3 M1                          1
48                Minotaur V                          1
49      Falcon 9 Full Thrust                          1
50                  Electron                          1
51              Ariane 5 ECA                          1
52                   LVM3 M4                          1
53         Soyuz-2.1b/Fregat                          1